# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: deploy-ms-api

on:
  push:
    branches: ["main"]

jobs:
  deploy-ms-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'hello world ...'
      - run: ls -la
      - run: touch .env
      - run: echo 'DATABASE_URL=${{secrets.MS_CONN}}'  >> .env
      - run: cat .env
      - run: docker build -t echodavid/nodejs-restapi-mysql:${{github.sha}} .
      - run: docker images
   
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name: docker push
        run:  docker push ${{ secrets.DOCKER_USER}}/nodejs-restapi-mysql:${{github.sha}}   

